<a href="https://colab.research.google.com/github/delademf/cv_deeplearning_tenserflow/blob/main/tensorflow_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import tensorflow as tf

In [9]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [10]:
tensor_one_d = tf.constant([2,1,4])
print(tensor_one_d)

tf.Tensor([2 1 4], shape=(3,), dtype=int32)


In [11]:
tensor_two_d = tf.constant([[2,1,4],
                            [3,1,5],
                            [2,4,7],
                            [9,5,6]])
print(tensor_two_d)

tf.Tensor(
[[2 1 4]
 [3 1 5]
 [2 4 7]
 [9 5 6]], shape=(4, 3), dtype=int32)


In [12]:
tensor_three_d = tf.constant([[[1,3,6],
                                [1,4,5]],
                              [[3,6,6],
                                [9,4,5]],
                              [[4,3,7],
                                [7,4,5]],
                              [[11,36,6],
                                [1,34,0]],
                             ])
print(tensor_three_d)

tf.Tensor(
[[[ 1  3  6]
  [ 1  4  5]]

 [[ 3  6  6]
  [ 9  4  5]]

 [[ 4  3  7]
  [ 7  4  5]]

 [[11 36  6]
  [ 1 34  0]]], shape=(4, 2, 3), dtype=int32)


In [13]:
print(tensor_three_d.shape)

(4, 2, 3)


In [14]:
print(tensor_three_d.ndim)

3


the above output "3" shoe the dimension

In [15]:
tensor_four_d = tf.constant([[[[1,3,6],
                                [1,4,5]],
                              [[3,6,6],
                                [9,4,5]],
                              [[4,3,7],
                                [7,4,5]],
                              [[11,36,6],
                                [1,34,0]],
                             ],
                             [[[1,3,6],
                                [1,4,5]],
                              [[3,6,6],
                                [9,4,5]],
                              [[4,3,7],
                                [7,4,5]],
                              [[11,36,6],
                                [1,34,0]],
                             ],
                             [[[1,3,6],
                                [1,4,5]],
                              [[3,6,6],
                                [9,4,5]],
                              [[4,3,7],
                                [7,4,5]],
                              [[11,36,6],
                                [1,34,0]],
                             ]
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1  3  6]
   [ 1  4  5]]

  [[ 3  6  6]
   [ 9  4  5]]

  [[ 4  3  7]
   [ 7  4  5]]

  [[11 36  6]
   [ 1 34  0]]]


 [[[ 1  3  6]
   [ 1  4  5]]

  [[ 3  6  6]
   [ 9  4  5]]

  [[ 4  3  7]
   [ 7  4  5]]

  [[11 36  6]
   [ 1 34  0]]]


 [[[ 1  3  6]
   [ 1  4  5]]

  [[ 3  6  6]
   [ 9  4  5]]

  [[ 4  3  7]
   [ 7  4  5]]

  [[11 36  6]
   [ 1 34  0]]]], shape=(3, 4, 2, 3), dtype=int32)


casting expalnation

In [22]:
tensor_one_d = tf.constant([1,2.0,-3,90],dtype= tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype= tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 1.  2. -3. 90.], shape=(4,), dtype=float32)
tf.Tensor([ 1  2 -3 90], shape=(4,), dtype=int16)


you can use a boolean d tpye

In [24]:
tensor_bool = ([True,False,True])
print(tensor_bool)

[True, False, True]


In [23]:
tensor_one_d = tf.constant([1,2,0,-3,90],dtype= tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype= tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 1.  2.  0. -3. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True  True False  True  True], shape=(5,), dtype=bool)


In [26]:
import numpy as np

In [27]:
np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [28]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [31]:
# this produces an identity matrix
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,#this talk about the number of batches for the matrics
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)


tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


the code below fills the dimensioned matrix with the value 5 or any your choose but in all postions

In [33]:
fill_tensor=tf.fill(
    [3,4], 5, name=None
)
print (fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


fill the dimensioned matrix with only one

In [35]:
ones_tensor = tf.ones(
    shape=[3,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [36]:
zeros_tensor = tf.zeros(
    shape=[3,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [37]:
print(tensor_three_d.shape)

(4, 2, 3)


The rank of a tensor is the number of indices required to uniquely select each element of the tensor

In [39]:
t = tf.constant([[1,4,6],[9,3,5]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [40]:
t = tf.constant([[1,4,6],[9,3,5]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

decrease in sigma make curve narrower

In [44]:
random_tensor=tf.random.normal(
    shape=[3,4],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 1.5740057   2.1918716  -0.01999852 -0.8914747 ]
 [ 0.70352685  0.2698522   0.51343876  2.3300931 ]
 [-0.44288072 -0.01650855  1.2066219  -0.6623804 ]], shape=(3, 4), dtype=float32)


the difference between the uniform and the normal is that with the random.uniform the chances of it getting picked are uniform


In [50]:
random_uniform=tf.random.uniform(
    shape=[3,3],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_uniform)

tf.Tensor(
[[ 5 73 71]
 [96 96 17]
 [89 80 59]], shape=(3, 3), dtype=int32)
